name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    name: PHP 8.2 - Laravel 11.*

    steps:
      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: ~/.composer/cache/files
            key: dependencies-laravel-11-php-8.2-composer-${{ hashFiles('composer.json') }}

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.2
            extensions: dom, curl, libxml, mbstring, zip
            coverage: none

      -   name: Install dependencies
          run: |
            composer require "laravel/framework:11.*" "orchestra/testbench:9.*" --no-interaction --no-update
            composer update --prefer-dist --no-interaction --no-progress

      -   name: Execute tests
          run: vendor/bin/phpunit
